### ISSUE TITLE
[Auth] 로그인, 회원가입 JWT 관련 이슈

### ISSUE THREAD

**Issue by Im-younique** [SWAcademy-Team-3/todoclient#43]
JWT를 저장하는 과정에서 많은 시행착오를 겪고 있습니다.

1. private variable에만 저장하는 방법.
 - 보안적으로 안전하지만, 새로고침시 로그인 정보가 날아가기 때문에 추후 앱으로 구현되었을 때, 앱을 킬 때마다 로그인 해야하는 불편함이 있습니다.
 
2. cookie에 front에서 저장하는 방법
 - XSS (공격자의 악의적인 js 코드를 주입하여 공격하는 기법으로 code injection attack이다.) 로 부터 안전하지 않습니다. 
 - 이는 프론트쪽에서 httpOnly 옵션은 넣을 수 없기 때문에 백엔드 단에서 httpOnly옵션을 붙여서 쿠키를 보호하는 방법으로 XSS 공격을 어느정도 막을 수 있습니다.
 - ! 여기서부터 문제인데, 백엔드 쪽에서 setCookie를 헤더에 넣어서 쿠키를 저장하려고 했지만 브라우저 상에는 남지 않는 문제가 발생하고 있습니다. 이를 해결하는 방법이 제일 보안상 안전해 보이긴 합니다.
 - CSRF (request를 가로채 공격하는 방법) 공격으로 부터는 자유롭지 못한 것이 단점입니다.
 
3. localStorage에 저장하는 방법
 - CSRF 공격으로 부터는 안전한것이 js 코드로 부터 헤더에 담기 때문에 안전합니다.
 - XSS 공격에 매우 취약합니다. 로컬 스토리지에 있는 값을 공격자가 볼 수 있기 때문입니다.
 
=> 현재 선택된 방법은 받은 jwt access_token 값을 쿠키에 저장해놓고 사용 중 입니다. httpOnly 옵션없이... 매우 보안에 취약한 문제이기 때문에 추후에 배포 전 반드시 수정해야합니다.
p.s. cookie에 저장된 값은 헤더에 자동으로 붙어 날아가기 때문에 굳이 js 코드로 넣어주지 않아도 된다는데 이게 맞나...?
+) 만약 그렇다면 key 값은 Authentication이라고 붙이고 Bearer {token} 을 value로 설정해야하는 것인가...? 

Solution은 httpOnly 옵션이 붙은 jwt 토큰이 담긴 쿠키를 사용하고, refresh token을 활용하여 access Token을 자주 갈아주는 것이 제일 많이 쓰이는 방법인 것 같습니다. 이 외에 좋은 방법이 있다면 추후에 업데이트 해보겠습니다.

**Comment by kingseungwooya** [comment]
현재 선택된 방법은 받은 jwt access_token 값을 쿠키에 저장해놓고 사용 중 입니다. httpOnly 옵션없이... 매우 보안에 취약한 문제이기 때문에 추후에 배포 전 반드시 수정해야합니다.
p.s. cookie에 저장된 값은 헤더에 자동으로 붙어 날아가기 때문에 굳이 js 코드로 넣어주지 않아도 된다는데 이게 맞나...?
+) 만약 그렇다면 key 값은 Authentication이라고 붙이고 Bearer {token} 을 value로 설정해야하는 것인가...?

Solution은 httpOnly 옵션이 붙은 jwt 토큰이 담긴 쿠키를 사용하고, refresh token을 활용하여 access Token을 자주 갈아주는 것이 제일 많이 쓰이는 방법인 것 같습니다. 이 외에 좋은 방법이 있다면 추후에 업데이트 해보겠습니다.


--> 현재 서버에서 PostMan에서는 cookie에 setting이 되지만 이상하게 web browser 상에서 이루어지지 않고 있는데 그 방법에 대해 다시 의논하고 해결했으면 합니다.
